### NUMPY :

> Why NumPy is Fast — The Role of C

1. Internally implemented in C: NumPy's core array operations are written in compiled C, which is much faster than Python.

2. No Python loops: When you do array1 + array2, NumPy doesn't loop in Python — it executes compiled C code behind the scenes.

3. Vectorization: NumPy uses SIMD (Single Instruction, Multiple Data) under the hood.

4. Contiguous memory allocation: Unlike lists, NumPy stores arrays in continuous blocks of memory, speeding up access. no need reference like lists

5. So when we run a array it runs as a whole block while in loop it iterates over which makes it slower

6. NumPy (Numerical Python) is used for:
     1. Fast mathematical operations on arrays even can handle large number of data
     2. Handling large datasets
     3. Vector and matrix operations

eg : image of black hole (using 8 diffrent telescopes are arranged 350 terrabyte of data is obtained per day in the telescope to generate the image they used numpy) (event horizon telescope) - virtual telescope

7. in list the data is stored in different reference and the data has to bought by the reference

8. we are using numpy for data handling and data is stored in the form of arrays

#### IMPORTING NUMPY

In [1]:
import numpy as np

#### PROOF NUMPY IS FASTER THAN LISTS

In [2]:
# Eg
import time     # importing time
import numpy as np

# Python list
lst = list(range(1000000))
start = time.time() # running start time
lst = [x * 2 for x in lst]
print("List time:", time.time() - start) # running time - starting time

# NumPy array
arr = np.arange(1000000)
start = time.time()
arr = arr * 2
print("NumPy time:", time.time() - start)


List time: 0.16713571548461914
NumPy time: 0.005573749542236328


#### ARRAY CREATION

In [18]:
# 1 D array
arr1 = np.array([1,2,3,4,5])
print("1 dimensional array:\n",arr1)

#2 D array
arr2 = np.array([[1,2,3],[2,3,4],[4,5,6]])
print("\n2D array:\n", arr2)

#3 D array
arr3 = np.array([[[1,2,3],[2,3,4],[4,5,6]]])
print("\n3D array:\n", arr3)


1 dimensional array:
 [1 2 3 4 5]

2D array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

3D array:
 [[[1 2 3]
  [2 3 4]
  [4 5 6]]]


#### INSPECTING ARRAYS

In [88]:
# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr1.shape) #(row elements)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr1.ndim)

# CHECKING SIZE
print("THE SIZE OF ARRAY IS :", arr1.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr1.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr1.dtype.name)


# CHECKING BYTES
print("ITEM SIZE:",arr1.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr1.nbytes)  # no of elements * size of each element == 5*8 ==40




THE SHAPE OF ARRAY IS : (5,)
THE DIMENSION IS : 1
THE SIZE OF ARRAY IS : 5
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 40


In [87]:
# CHECKING ASPECTS FOR 2D ARRAY 

# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr2.shape) # (rows and columns)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr2.ndim)

# CHECKING SIZE  # total number of elements
print("THE SIZE OF ARRAY IS :", arr2.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr2.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr2.dtype.name)

# CHECKING BYTES
print("ITEM SIZE:",arr2.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr2.nbytes)  # no of elements * size of each element == 9*8 ==72


THE SHAPE OF ARRAY IS : (3, 3)
THE DIMENSION IS : 2
THE SIZE OF ARRAY IS : 9
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 72


In [89]:
# CHECKING ASPECTS FOR 3D ARRAY 

# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr3.shape) # (block,rows,columns)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr3.ndim)

# CHECKING SIZE
print("THE SIZE OF ARRAY IS :", arr3.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr3.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr3.dtype.name)

# CHECKING BYTES
print("ITEM SIZE:",arr3.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr3.nbytes)  # no of elements * size of each element == 9*8 ==72


THE SHAPE OF ARRAY IS : (1, 3, 3)
THE DIMENSION IS : 3
THE SIZE OF ARRAY IS : 9
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 72


In [45]:
#### ARRAY CREATION

# ZERO ARRAY 
print("ZERO ARRAY:\n",np.zeros([3,3], dtype="int64"))

# ONES
print ("\nONES:\n",np.ones([3,3]))

# 3D ones
print("\n3D ONES:\n",np.ones([3,3,3],dtype="int64"))

# IDENTICAL ARRAY or MATRIX
print("\nIDENTICAL MATRIX:\n",np.eye(3))

# ARANGE --- (start, stop, step)
print("\nARANGE:\n", np.arange(-5,30,5))

# LINSPACE -- (start, stop, num_samples) --- linearly spaced values 
print("\nLINSPACE:\n",np.linspace(0,1,10))

# FILLING EMPTY ARRAY  # FILLING VALUES 
print("\nFILL VALUE :\n",np.full([3,3], 10))

# RANDOM MATRIX : FLOAT ARRAY
print("\n RANDOM MATRIX:\n",np.random.rand(2, 3) ) # 2 rows, 3 columns # float array

#RANDOM INT 
print("\n RANDOM INT :\n",np.random.randint(0, 10, size=(2, 3)))

#EMPTY MATRIX
n5 = np.empty([1,3])
print("\nEMPTY MATRIX:\n",np.empty([1,3]))

# FILLING EMPTY ARRAY 
n5.fill(99)

# 

ZERO ARRAY:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

ONES:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3D ONES:
 [[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]

IDENTICAL MATRIX:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ARANGE:
 [-5  0  5 10 15 20 25]

LINSPACE:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

FILL VALUE :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

 RANDOM MATRIX:
 [[0.16089174 0.26026579 0.10238879]
 [0.08432089 0.24977886 0.33130775]]

 RANDOM INT :
 [[4 2 8]
 [5 3 3]]

EMPTY MATRIX:
 [[99. 99. 99.]]


#### ACCESSING ELEMENTS

In [57]:
# NumPy slicing: arr[i], arr[i:j], arr[start:stop:step]
# 1D ARRAY
print("\n ARRAY1:",arr1)
print("\n 3RD ELEMENT IN 1 D :",arr1[2])
print("\n SLICING IN 1D:",arr1[1:])
print("\n START STOP STEP SLICING:",arr1[0:2:1])
print("\n REVERSE :", arr1[::-1])


 ARRAY1: [1 2 3 4 5]

 3RD ELEMENT IN 1 D : 3

 SLICING IN 1D: [2 3 4 5]

 START STOP STEP SLICING: [1 2]

 REVERSE : [5 4 3 2 1]


In [71]:
#For multidim, arr[row, col], arr[:, col], arr[row_slice, col_slice] 
#2D ARRAY
print("\n2D ARRAY :\n", arr2)
print("\n2nd row 1st value :",arr2[1,0])
print("\n 3rd COLUMNS:", arr2[:,2])
print("\n 2nd ROWS:",arr2[1,:])




2D ARRAY :
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

2nd row 1st value : 2

 3rd COLUMNS: [3 4 6]

 2nd ROWS: [2 3 4]

 row and column slice: [[1 2]
 [2 3]]


In [79]:
print("\n row and column slice:\n", arr2[0:2,0:2])

print("\n THE ARRAY:\n",arr2)

print("\n THE 1st row and 2nd row and 2nd column and 3rd column:\n",arr2[0:2, 1:3])
#Boolean indexing: arr[arr > value]


 row and column slice:
 [[1 2]
 [2 3]]

 THE ARRAY:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

 THE 1st row and 2nd row and 2nd column and 3rd column:
 [[2 3]
 [3 4]]


In [85]:
# for 3D
print("3D ARRAY:\n",arr3)

# indexing for 3d array
print("indexing:",arr3[0,0,1])

# changing the value
arr3[0,1,2]=10
arr3

3D ARRAY:
 [[[ 1  2  3]
  [ 2  3 10]
  [ 4  5  6]]]
indexing: 2


array([[[ 1,  2,  3],
        [ 2,  3, 10],
        [ 4,  5,  6]]])

In [ ]:
#### IMPORTANT : INDEX STARTS WITH 0 

In [93]:
### SORT 
n10 = np.random.randint(1,20,size=(10,))
print(n10)
print("SORTING :",np.sort(n10))

[ 2  7 17  2  9 16 17  3 18 12]
SORTING : [ 2  2  3  7  9 12 16 17 17 18]


In [ ]:
### 2D array sort
