### NUMPY :

> Why NumPy is Fast — The Role of C

1. Internally implemented in C: NumPy's core array operations are written in compiled C, which is much faster than Python.

2. No Python loops: When you do array1 + array2, NumPy doesn't loop in Python — it executes compiled C code behind the scenes.

3. Vectorization: NumPy uses SIMD (Single Instruction, Multiple Data) under the hood.

4. Contiguous memory allocation: Unlike lists, NumPy stores arrays in continuous blocks of memory, speeding up access. no need reference like lists

5. So when we run a array it runs as a whole block while in loop it iterates over which makes it slower

6. NumPy (Numerical Python) is used for:
     1. Fast mathematical operations on arrays even can handle large number of data
     2. Handling large datasets
     3. Vector and matrix operations

eg : image of black hole (using 8 diffrent telescopes are arranged 350 terrabyte of data is obtained per day in the telescope to generate the image they used numpy) (event horizon telescope) - virtual telescope

7. in list the data is stored in different reference and the data has to bought by the reference

8. we are using numpy for data handling and data is stored in the form of arrays

| **Function / Concept** | **Description**             | **Example**           | **Output**                     |
| ---------------------- | --------------------------- | --------------------- | ------------------------------ |
| `np.array()`           | Creates NumPy array         | `np.array([1, 2, 3])` | `[1 2 3]`                      |
| `np.zeros((2, 3))`     | 2x3 array of zeros          |                       | `[[0. 0. 0.], [0. 0. 0.]]`     |
| `np.ones((2, 2))`      | 2x2 array of ones           |                       | `[[1. 1.], [1. 1.]]`           |
| `np.arange(1, 10, 2)`  | Range with step             |                       | `[1 3 5 7 9]`                  |
| `np.linspace(0, 1, 5)` | Even spacing                |                       | `[0. , 0.25, 0.5 , 0.75, 1. ]` |
| `.shape`               | Returns shape               | `a.shape`             | e.g., `(2, 3)`                 |
| `.reshape()`           | Changes shape               | `a.reshape(3, 2)`     | 3 rows × 2 cols                |
| `.flatten()`           | Converts to 1D              |                       | `[1 2 3 4]`                    |
| `.mean()`              | Average value               | `a.mean()`            | `2.5` (for `[1,2,3,4]`)        |
| `.max()` / `.min()`    | Max/Min value               | `a.max()`             | `4`                            |
| `np.hstack()`          | Stack arrays horizontally   | `np.hstack((a, b))`   | `[1 2 3 1 2 3]`                |
| `np.vstack()`          | Stack arrays vertically     | `np.vstack((a, b))`   | `[[1 2 3],[1 2 3]]`            |
| `np.split()`           | Splits array into subarrays | `np.split(a, 2)`      | Two halves of `a`              |
| Indexing/Slicing       | Access parts of array       | `a[1:3]`, `a[:, 1]`   | Slice or column access         |


#### IMPORTING NUMPY

In [1]:
import numpy as np

#### PROOF NUMPY IS FASTER THAN LISTS

In [2]:
# Eg
import time     # importing time
import numpy as np

# Python list
lst = list(range(1000000))
start = time.time() # running start time
lst = [x * 2 for x in lst]
print("List time:", time.time() - start) # running time - starting time

# NumPy array
arr = np.arange(1000000)
start = time.time()
arr = arr * 2
print("NumPy time:", time.time() - start)


List time: 0.0921175479888916
NumPy time: 0.003907918930053711


#### ARRAY CREATION

In [3]:
# 1 D array
arr1 = np.array([1,2,3,4,5])
print("1 dimensional array:\n",arr1)

#2 D array
arr2 = np.array([[1,2,3],[2,3,4],[4,5,6]])
print("\n2D array:\n", arr2)

#3 D array
arr3 = np.array([[[1,2,3],[2,3,4],[4,5,6]]])
print("\n3D array:\n", arr3)


1 dimensional array:
 [1 2 3 4 5]

2D array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

3D array:
 [[[1 2 3]
  [2 3 4]
  [4 5 6]]]


#### INSPECTING ARRAYS

In [4]:
# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr1.shape) #(row elements)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr1.ndim)

# CHECKING SIZE
print("THE SIZE OF ARRAY IS :", arr1.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr1.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr1.dtype.name)


# CHECKING BYTES
print("ITEM SIZE:",arr1.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr1.nbytes)  # no of elements * size of each element == 5*8 ==40




THE SHAPE OF ARRAY IS : (5,)
THE DIMENSION IS : 1
THE SIZE OF ARRAY IS : 5
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 40


In [5]:
# CHECKING ASPECTS FOR 2D ARRAY 

# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr2.shape) # (rows and columns)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr2.ndim)

# CHECKING SIZE  # total number of elements
print("THE SIZE OF ARRAY IS :", arr2.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr2.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr2.dtype.name)

# CHECKING BYTES
print("ITEM SIZE:",arr2.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr2.nbytes)  # no of elements * size of each element == 9*8 ==72


THE SHAPE OF ARRAY IS : (3, 3)
THE DIMENSION IS : 2
THE SIZE OF ARRAY IS : 9
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 72


In [6]:
# CHECKING ASPECTS FOR 3D ARRAY 

# CHECKING SHAPE
print("THE SHAPE OF ARRAY IS :", arr3.shape) # (block,rows,columns)

# CHECKING DIMENSION
print("THE DIMENSION IS :",arr3.ndim)

# CHECKING SIZE
print("THE SIZE OF ARRAY IS :", arr3.size)

# CHECKING DATA TYPE
print("THE DATA TYPE OF ARRAY IS :", arr3.dtype)

# NAME OF DATA TYPE
print("THE DATA TYPE IS : ", arr3.dtype.name)

# CHECKING BYTES
print("ITEM SIZE:",arr3.itemsize) # space for each element stored

# CHECKING BYTES
print("TOTAL BYTES:",arr3.nbytes)  # no of elements * size of each element == 9*8 ==72


THE SHAPE OF ARRAY IS : (1, 3, 3)
THE DIMENSION IS : 3
THE SIZE OF ARRAY IS : 9
THE DATA TYPE OF ARRAY IS : int64
THE DATA TYPE IS :  int64
ITEM SIZE: 8
TOTAL BYTES: 72


In [7]:
#### ARRAY CREATION

# ZERO ARRAY 
print("ZERO ARRAY:\n",np.zeros([3,3], dtype="int64"))

# ONES
print ("\nONES:\n",np.ones([3,3]))

# 3D ones
print("\n3D ONES:\n",np.ones([3,3,3],dtype="int64"))

# IDENTICAL ARRAY or MATRIX
print("\nIDENTICAL MATRIX:\n",np.eye(3))

# ARANGE --- (start, stop, step)
print("\nARANGE:\n", np.arange(-5,30,5))

# LINSPACE -- (start, stop, num_samples) --- linearly spaced values 
print("\nLINSPACE:\n",np.linspace(0,1,10))

# FILLING EMPTY ARRAY  # FILLING VALUES 
print("\nFILL VALUE :\n",np.full([3,3], 10))

# RANDOM MATRIX : FLOAT ARRAY
print("\n RANDOM MATRIX:\n",np.random.rand(2, 3) ) # 2 rows, 3 columns # float array

#RANDOM INT 
print("\n RANDOM INT :\n",np.random.randint(0, 10, size=(2, 3)))

#EMPTY MATRIX
n5 = np.empty([1,3])
print("\nEMPTY MATRIX:\n",np.empty([1,3]))

# FILLING EMPTY ARRAY 
n5.fill(99)

# 

ZERO ARRAY:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

ONES:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3D ONES:
 [[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]

IDENTICAL MATRIX:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ARANGE:
 [-5  0  5 10 15 20 25]

LINSPACE:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

FILL VALUE :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

 RANDOM MATRIX:
 [[0.75293487 0.40878624 0.29125604]
 [0.97531932 0.2866858  0.33664568]]

 RANDOM INT :
 [[1 5 9]
 [9 2 3]]

EMPTY MATRIX:
 [[1. 1. 1.]]


#### ACCESSING ELEMENTS

In [8]:
# NumPy slicing: arr[i], arr[i:j], arr[start:stop:step]
# 1D ARRAY
print("\n ARRAY1:",arr1)
print("\n 3RD ELEMENT IN 1 D :",arr1[2])
print("\n SLICING IN 1D:",arr1[1:])
print("\n START STOP STEP SLICING:",arr1[0:2:1])
print("\n REVERSE :", arr1[::-1])


 ARRAY1: [1 2 3 4 5]

 3RD ELEMENT IN 1 D : 3

 SLICING IN 1D: [2 3 4 5]

 START STOP STEP SLICING: [1 2]

 REVERSE : [5 4 3 2 1]


In [9]:
#For multidim, arr[row, col], arr[:, col], arr[row_slice, col_slice] , arr[row ,:]
#2D ARRAY
print("\n2D ARRAY :\n", arr2)
print("\n2nd row 1st value :",arr2[1,0])
print("\n 3rd COLUMNS:", arr2[:,2])
print("\n 2nd ROWS:",arr2[1,:])




2D ARRAY :
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

2nd row 1st value : 2

 3rd COLUMNS: [3 4 6]

 2nd ROWS: [2 3 4]


In [10]:
print("\n row and column slice:\n", arr2[0:2,0:2])

print("\n THE ARRAY:\n",arr2)

print("\n THE 1st row and 2nd row and 2nd column and 3rd column:\n",arr2[0:2, 1:3])
#Boolean indexing: arr[arr > value]


 row and column slice:
 [[1 2]
 [2 3]]

 THE ARRAY:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

 THE 1st row and 2nd row and 2nd column and 3rd column:
 [[2 3]
 [3 4]]


In [11]:
# for 3D
print("3D ARRAY:\n",arr3)

# indexing for 3d array
print("indexing:",arr3[0,0,1])

# changing the value
arr3[0,1,2]=10
arr3

3D ARRAY:
 [[[1 2 3]
  [2 3 4]
  [4 5 6]]]
indexing: 2


array([[[ 1,  2,  3],
        [ 2,  3, 10],
        [ 4,  5,  6]]])

In [12]:
#### IMPORTANT : INDEX STARTS WITH 0 

In [13]:
### SORT 
n10 = np.random.randint(1,20,size=(10,))
print(n10)
print("SORTING :",np.sort(n10))

[13  6  3 10 10 16  1  6  6  5]
SORTING : [ 1  3  5  6  6  6 10 10 13 16]


In [14]:
### 2D array sort == row wise axis = 1 default =1
n11= np.array([[1,2,5],[8,4,3],[3,6,2]])
n11.sort()
n11

array([[1, 2, 5],
       [3, 4, 8],
       [2, 3, 6]])

In [15]:
## to sort column wise -- axis = 0
n11.sort(axis=0)
n11


array([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 8]])

#### RESHAPE AND ARRAY CONVERSION

In [16]:
n12= n10.reshape(5,2)  # np.reshape(row, col)
print(n12)
n13 = n10.reshape(1,5,2) # np.reshape(block , rows , col)
print(n13)
print(n10.reshape((1, -1))) # -1 decides the number of columns itself , just need to enter the row number accordingly and -1 calculates the number of columns
n10.reshape((5,-1))
n10.reshape((1,5,-1))

[[13  6]
 [ 3 10]
 [10 16]
 [ 1  6]
 [ 6  5]]
[[[13  6]
  [ 3 10]
  [10 16]
  [ 1  6]
  [ 6  5]]]
[[13  6  3 10 10 16  1  6  6  5]]


array([[[13,  6],
        [ 3, 10],
        [10, 16],
        [ 1,  6],
        [ 6,  5]]], dtype=int32)

In [17]:
# CONCATENATE (joining two array)

n13= np.arange(4)
n14 = np.arange(5,9)
n15 = np.concatenate((n13,n14))
n15

array([0, 1, 2, 3, 5, 6, 7, 8])

In [18]:
## flatten() vs ravel() – Convert to 1D
# flatten - converts to 1D and does not return  the value
# ravel - returns the value
a = np.array([[1, 2], [3, 4]])
a.flatten()  # Output: array([1, 2, 3, 4])
a.ravel()    # Output: array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [19]:
#reshape(-1) – Auto Flatten
n11.reshape(-1)
# flatten changed its own copy, not original. It creates a copy and does not edit the original
# ravel  and reshapes affected the original array, because they returned views. 

array([1, 2, 5, 2, 3, 6, 3, 4, 8])

In [20]:
# to list converts into pythonlists
arr = np.array([[1, 2], [3, 4]])
arr.tolist()  # Output: [[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [21]:
# astype converts to desired type
arr = np.array([1.5, 2.7])
arr_int = arr.astype(int)

In [22]:
#np.array() – List to NumPy Array
lst = [1, 2, 3]
arr = np.array(lst)
arr

array([1, 2, 3])

In [23]:
#np.resize() vs reshape()
#reshape() only works if the total size matches.
#resize() can repeat data or truncate to match size.
a = np.array([1, 2, 3])
np.resize(a, (2, 4)) 

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

In [24]:
# newaxis -- to convert 1D to 2D
n16 = np.arange(8)
print(n16)
n17 = n16[np.newaxis,:]
print(n17)
n18 = n16[:,np.newaxis]
print(n18)


[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [25]:
# expand dims
n19 = np.expand_dims(n16,axis=1)
print(n19)
n20 = np.expand_dims(n16,axis=0)
print(n20)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0 1 2 3 4 5 6 7]]


#### ADVANCED INDEXING AND SLIICNG

In [26]:
n21 = np.arange(10)
n21
print(n21[n21<5]) # condition

[0 1 2 3 4]


In [27]:
print(n21[(n21>3) & (n21<9)])

[4 5 6 7 8]


In [28]:
five_up = n21>5 # it checks all the elements inside array and stores as boolean and then returns the value that are true
print(five_up) 
print(n21[five_up])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [29]:
n21[2] = 100
print(np.nonzero(n21)) # it gives the index values 

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [30]:
print(n21[2:7])

[100   3   4   5   6]


#### STACK AND SPLIT

In [31]:
n22 = np.array([[1,2],[3,4]])
n23 = np.array([[5,6],[7,8]])
np.vstack((n22,n23)) # vertical stacking
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
n24 = np.arange(1,21)
np.hsplit(n24 ,4) # it splits array into 4 different array 
# vsplit works for 3d conditions or 2d array only

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [34]:
#### SHALLOW COPY 
n25 = n24  # it copies the reference and hence changes in one array affects the other # only one array 
n25[0] = 100
print(n25)
print(n24)

[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [35]:
#### DEEP COPY
n26 = n24.copy() # it creates a new copy and then alters the array 
n24[0]=200
print(n24)
print(n26)

[200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


#### MATH

In [36]:
print(n24)
print(n26)
print(n24+n26) #adds element with the ellement in other matrices

[200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[300   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40]


In [37]:
print(n24 *2)

[400   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40]


In [38]:
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26.std())
print(n26.mean())

309
100
2
20.118337406455833
15.45
